name: HRRR-db
channels:
- pyviz
- conda-forge
dependencies:
- bokeh
- boto3
- botocore
- cfgrib
- dask
- dask-expr
- graphviz
- holoviews
- ipython
- metpy
- psycopg
- python-dotenv
- s3fs
- sqlalchemy
- xarray
- zarr
